// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type {
  StoryblokRichtext,
  StoryblokAsset,
  StoryblokMultilink,
  StoryblokMultiasset,
} from "../storyblok.d.ts";
export interface Accordion {
  items?: AccordionItem[];
  component: "accordion";
  _uid: string;
  [k: string]: unknown;
}

export interface AccordionItem {
  title?: string;
  subitems?: AccordionSubitem[];
  component: "accordion_item";
  _uid: string;
  [k: string]: unknown;
}

export interface AccordionSubitem {
  title?: string;
  description?: StoryblokRichtext;
  component: "accordion_subitem";
  _uid: string;
  [k: string]: unknown;
}

export interface Advantage {
  text?: string;
  component: "advantage";
  _uid: string;
  [k: string]: unknown;
}

export interface BenefitItem {
  text: string;
  component: "benefit item";
  _uid: string;
  [k: string]: unknown;
}

export interface Benefits {
  final_text_intro: string;
  final_action_btn_text: string;
  final_action_btn_link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  items?: BenefitItem[];
  component: "benefits";
  _uid: string;
  [k: string]: unknown;
}

export interface Brandstory {
  title?: string;
  column?: Story[];
  component: "brandstory";
  _uid: string;
  [k: string]: unknown;
}

export interface Button {
  svg_icon_light?: StoryblokAsset;
  btn_text: string;
  btn_link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface Buttons {
  column?: Button[];
  component: "buttons";
  _uid: string;
  [k: string]: unknown;
}

export interface CircularAnimation {
  steps?: CircularAnimationStepInfo[];
  media: StoryblokAsset;
  component: "circular_animation";
  _uid: string;
  [k: string]: unknown;
}

export interface CircularAnimationStepInfo {
  svg_icon_light?: StoryblokAsset;
  name?: string;
  title?: string;
  component: "circular_animation_step_info";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactForm {
  title?: string;
  subtitle?: string;
  component: "contact_form";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactInfo {
  hero_info?: StoryblokRichtext;
  address?: StoryblokRichtext;
  opening_day?: string;
  opening_hours?: StoryblokRichtext;
  component: "contact_info";
  _uid: string;
  [k: string]: unknown;
}

export interface DataItem {
  lead?: string;
  description?: StoryblokRichtext;
  component: "data_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Faq {
  hero_text_initial?: string;
  hero_text_last?: string;
  hero_description?: StoryblokRichtext;
  search_placeholder_text?: string;
  column?: Accordion[];
  robots?: Robots[];
  seo_metadata?: unknown;
  component: "faq";
  _uid: string;
  [k: string]: unknown;
}

export interface FeatureSection {
  title?: string;
  description?: StoryblokRichtext;
  media?: StoryblokAsset;
  component: "feature_section";
  _uid: string;
  [k: string]: unknown;
}

export interface FeatureSectionsContainer {
  column?: FeatureSection[];
  component: "feature_sections_container";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  column?: (FooterLeft | FooterRight)[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterItem {
  items?: (Links | Info)[];
  component: "footer_item";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterLeft {
  items?: (Links | Info)[];
  component: "footer_left";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterRight {
  items?: (Info | Links)[];
  component: "footer_right";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterSchema {
  name?: string;
  url?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  logo?: StoryblokAsset;
  streetAddress?: string;
  addressLocality?: string;
  postalCode?: string;
  addressCountry?: string;
  telephone?: string;
  email?: string;
  contactType?: string;
  availableLanguage?: ("" | "en" | "de")[];
  social_links?: string;
  component: "footer_schema";
  _uid: string;
  [k: string]: unknown;
}

export interface Global {
  burger_menu?: Menu[];
  footer?: FooterItem[];
  footer_schema_information?: FooterSchema[];
  contact_details?: ContactInfo[];
  login_btn_redirection_link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  jammer_text?: string;
  jammer_text_count?: string;
  component: "global";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (
    | Accordion
    | AccordionItem
    | AccordionSubitem
    | Advantage
    | BenefitItem
    | Benefits
    | Brandstory
    | Button
    | Buttons
    | CircularAnimation
    | CircularAnimationStepInfo
    | ContactForm
    | ContactInfo
    | DataItem
    | Faq
    | FeatureSection
    | FeatureSectionsContainer
    | Footer
    | FooterItem
    | FooterLeft
    | FooterRight
    | FooterSchema
    | Global
    | Grid
    | Hero
    | Imprint
    | ImprintItem
    | Info
    | Item
    | Links
    | ListWithItems
    | Menu
    | MenuItem
    | Module
    | ModuleEntity
    | ModuleIntro
    | Modules
    | ModulesDetailsSchema
    | ModulesSchema
    | Page
    | Pricing
    | PricingComparison
    | PricingComparisonContainer
    | PricingContainer
    | Robots
    | Section
    | SectionWithAdvantages
    | SectionWithBtnCircularAnimationContainer
    | SectionWithDataItem
    | Slider
    | Story
    | SubMenu
    | Team
    | TeamContainer
    | TrialForm
    | TrialRestrictionSchema
    | Version
  )[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Hero {
  svg_icon_light?: StoryblokAsset;
  headline?: string;
  description?: string;
  component: "hero";
  _uid: string;
  [k: string]: unknown;
}

export interface Imprint {
  title?: string;
  items?: ImprintItem[];
  component: "imprint";
  _uid: string;
  [k: string]: unknown;
}

export interface ImprintItem {
  lead?: string;
  description?: StoryblokRichtext;
  component: "imprint_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Info {
  description?: StoryblokRichtext;
  component: "info";
  _uid: string;
  [k: string]: unknown;
}

export interface Item {
  text?: string;
  should_icon_show?: boolean;
  component: "item";
  _uid: string;
  [k: string]: unknown;
}

export interface Links {
  text?: string;
  link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  component: "links";
  _uid: string;
  [k: string]: unknown;
}

export interface ListWithItems {
  title?: string;
  column?: Item[];
  component: "list_with_items";
  _uid: string;
  [k: string]: unknown;
}

export interface Menu {
  items?: MenuItem[];
  contact_menu?: string;
  component: "menu";
  _uid: string;
  [k: string]: unknown;
}

export interface MenuItem {
  Title?: string;
  link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  SubItems?: SubMenu[];
  component: "menu_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Module {
  column?: (Slider | Hero | Buttons | SectionWithAdvantages | FeatureSectionsContainer | Section)[];
  seo_metadata?: unknown;
  robots?: Robots[];
  schema_org_information?: ModulesDetailsSchema[];
  component: "module";
  _uid: string;
  [k: string]: unknown;
}

export interface ModuleEntity {
  name?: string;
  url?: string;
  featureList?: string;
  applicationCategory?: string;
  component: "module_entity";
  _uid: string;
  [k: string]: unknown;
}

export interface ModuleIntro {
  svg_icon_light: StoryblokAsset;
  module_name: string;
  image: StoryblokMultiasset;
  title: string;
  description: StoryblokRichtext;
  action_btn_svg_icon?: StoryblokAsset;
  action_btn_text: string;
  action_btn_link: string;
  is_action_btn_behavior_link?: boolean;
  component: "module_intro";
  _uid: string;
  [k: string]: unknown;
}

export interface Modules {
  column?: (Hero | ModuleIntro | Buttons | PricingContainer)[];
  schema_org_information?: ModulesSchema[];
  robots?: Robots[];
  seo_metadata?: unknown;
  component: "modules";
  _uid: string;
  [k: string]: unknown;
}

export interface ModulesDetailsSchema {
  name?: string;
  applicationCategory?: string;
  featureList?: string;
  description?: string;
  url?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  offers_price?: string;
  offers_price_currency?: string;
  offers_description?: string;
  publisher_name?: string;
  publisher_url?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  component: "modules_details_schema";
  _uid: string;
  [k: string]: unknown;
}

export interface ModulesSchema {
  name?: string;
  url?: string;
  description?: string;
  mainEntity?: ModuleEntity[];
  component: "modules_schema";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | Slider
    | Hero
    | Grid
    | Brandstory
    | Section
    | Benefits
    | Imprint
    | SectionWithDataItem
    | PricingComparisonContainer
    | Buttons
    | TeamContainer
    | SectionWithBtnCircularAnimationContainer
  )[];
  schema_org_information?: (TrialRestrictionSchema | ModulesSchema)[];
  robots?: Robots[];
  seo_metadata?: unknown;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Pricing {
  svg_icon?: StoryblokAsset;
  Name: string;
  description: string;
  feature_title: string;
  feature_list: StoryblokRichtext;
  price_text_monthly?: string;
  price_text_yearly?: string;
  bill_info_monthly?: string;
  bill_info_yearly?: string;
  action_btn_svg_icon?: StoryblokAsset;
  action_btn_text?: string;
  action_btn_link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  is_action_btn_behavior_link?: boolean;
  is_enterprise?: boolean;
  title_for_enterprise?: string;
  component: "pricing";
  _uid: string;
  [k: string]: unknown;
}

export interface PricingComparison {
  svg_icon?: StoryblokAsset;
  Name: string;
  price_text_monthly?: string;
  price_text_yearly?: string;
  column?: ListWithItems[];
  action_btn_svg_icon?: StoryblokAsset;
  action_btn_text?: string;
  is_enterprise?: boolean;
  title_for_enterprise?: string;
  component: "pricing_comparison";
  _uid: string;
  [k: string]: unknown;
}

export interface PricingComparisonContainer {
  toggle_text_1?: string;
  toggle_text_2?: string;
  column?: PricingComparison[];
  last_action_btn_text?: string;
  last_action_btn_link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  last_action_btn_svg_icon?: StoryblokAsset;
  component: "pricing_comparison_container";
  _uid: string;
  [k: string]: unknown;
}

export interface PricingContainer {
  toggle_text_1?: string;
  toggle_text_2?: string;
  column?: Pricing[];
  last_action_btn_text?: string;
  last_action_btn_link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  last_action_btn_svg_icon?: StoryblokAsset;
  component: "pricing_container";
  _uid: string;
  [k: string]: unknown;
}

export interface Robots {
  index?: boolean;
  follow?: boolean;
  component: "robots";
  _uid: string;
  [k: string]: unknown;
}

export interface Section {
  name?: string;
  title?: string;
  is_title_small?: boolean;
  description?: string;
  action_btn_svg_icon_light?: StoryblokAsset;
  action_btn_text?: string;
  action_btn_link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  component: "section";
  _uid: string;
  [k: string]: unknown;
}

export interface SectionWithAdvantages {
  name?: string;
  title?: string;
  advantages?: Advantage[];
  component: "section_with_advantages";
  _uid: string;
  [k: string]: unknown;
}

export interface SectionWithBtnCircularAnimationContainer {
  section?: Section[];
  buttons: Button[];
  animation?: CircularAnimation[];
  last_action_btn_svg_icon?: StoryblokAsset;
  last_action_btn_text?: string;
  last_action_btn_link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  component: "section_with_btn_circular_animation_container";
  _uid: string;
  [k: string]: unknown;
}

export interface SectionWithDataItem {
  title?: string;
  items?: (DataItem | Version)[];
  component: "section_with_data_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Slider {
  files?: StoryblokMultiasset;
  need_zoom_in_feature?: boolean;
  want_smaller_height?: boolean;
  component: "slider";
  _uid: string;
  [k: string]: unknown;
}

export interface Story {
  storyText?: string;
  component: "story";
  _uid: string;
  [k: string]: unknown;
}

export interface SubMenu {
  title?: string;
  link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  component: "sub_menu";
  _uid: string;
  [k: string]: unknown;
}

export interface Team {
  name?: string;
  caption?: string;
  image?: StoryblokAsset;
  component: "team";
  _uid: string;
  [k: string]: unknown;
}

export interface TeamContainer {
  column?: Team[];
  component: "team_container";
  _uid: string;
  [k: string]: unknown;
}

export interface TrialForm {
  title?: string;
  subtitle?: StoryblokRichtext;
  label_firstname?: string;
  label_surname?: string;
  label_name?: string;
  label_resturant_name?: string;
  label_email?: string;
  label_telephone?: string;
  radio_text_1?: string;
  radio_text_2?: string;
  privacy_policy_text?: StoryblokRichtext;
  terms_and_condition_text?: StoryblokRichtext;
  submit_button_text?: string;
  global_error?: string;
  success_message_headline?: string;
  success_message_subtitle?: string;
  success_message_btn?: string;
  disk_text_count?: string;
  disk_text?: string;
  seo_metadata?: unknown;
  robots?: Robots[];
  component: "trial_form";
  _uid: string;
  [k: string]: unknown;
}

export interface TrialRestrictionSchema {
  name?: string;
  price?: string;
  priceCurrency?: string;
  description?: string;
  featureList?: string;
  publisher_name?: string;
  publisher_url?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  component: "trial_restriction_schema";
  _uid: string;
  [k: string]: unknown;
}

export interface Version {
  text: string;
  version_number: string;
  component: "version";
  _uid: string;
  [k: string]: unknown;
}
